language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python3 manage.py migrate
script:
  - black --check blogging
  - black --check polling
  - black --check mysite
  - python3 manage.py test blogging
  - python3 manage.py test polling