language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python3 mysite/manage.py migrate
script:
  - python3 mysite/manage.py test blogging
  - python3 mysite/manage.py test polling